from odoo import fields, models
import io
import base64
import xlsxwriter


class BudgetVsActualReport(models.TransientModel):
    _name = "budget.vs.actual.report"
    _description = "Budget vs Actual Cost Report"

    name = fields.Char(
        string="Report Name",
        default="Budget vs Actual Cost Report",
        readonly=True,
    )

    def action_export_excel(self):
        self.ensure_one()

        output = io.BytesIO()

        workbook = xlsxwriter.Workbook(output, {"in_memory": True})
        worksheet = workbook.add_worksheet("Budget vs Actual")

        worksheet.center_horizontally()
        worksheet.set_row(0, 28)
        worksheet.set_row(1, 22)
        worksheet.set_row(5, 22)

        # ==========================
        # Formats
        # ==========================

        title_format = workbook.add_format({
            "bold": True,
            "font_size": 18,
            "font_color": "white",
            "bg_color": "#1F4E78",
            "align": "center",
            "valign": "vcenter",
        })

        report_title_format = workbook.add_format({
            "bold": True,
            "font_size": 13,
            "font_color": "#1F1F1F",
            "bg_color": "#D9EAD3",
            "border": 1,
            "align": "center",
            "valign": "vcenter",
        })

        header_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#4472C4",
            "border": 1,
            "align": "center",
            "valign": "vcenter",
        })

        text_format = workbook.add_format({
            "border": 1,
            "align": "left",
            "valign": "vcenter",
        })

        currency_format = workbook.add_format({
            "border": 1,
            "align": "right",
            "num_format": "#,##0.00",
        })

        total_text_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#305496",
            "border": 1,
            "align": "center",
        })

        total_currency_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#305496",
            "border": 1,
            "align": "right",
            "num_format": "#,##0.00",
        })

        info_label_format = workbook.add_format({
            "bold": True,
        })

        footer_format = workbook.add_format({
            "italic": True,
            "font_color": "#808080",
        })

        # ==========================
        # Company & Report Title
        # ==========================

        company = self.env.company

        worksheet.merge_range(
            "A1:E1",
            company.name,
            title_format,
        )

        worksheet.merge_range(
            "A2:E2",
            "Budget vs Actual Cost Report",
            report_title_format,
        )

        # ==========================
        # Report Information
        # ==========================

        worksheet.write("A4", "Report Date:", info_label_format)
        worksheet.write("B4", str(fields.Date.today()))

        worksheet.write("D4", "Generated By:", info_label_format)
        worksheet.write("E4", self.env.user.name)

        # ==========================
        # Headers
        # ==========================

        headers = [
            "Cost Center",
            "Budget",
            "Actual Cost",
            "Variance",
            "Remaining Budget",
        ]

        for col, header in enumerate(headers):
            worksheet.write(5, col, header, header_format)

        # ==========================
        # Column Width
        # ==========================

        worksheet.set_column("A:A", 30)
        worksheet.set_column("B:E", 20)

        # ==========================
        # Data
        # ==========================

        cost_centers = self.env["construction.cost.center"].search([])

        row = 6

        for cost_center in cost_centers:
            worksheet.write(
                row,
                0,
                cost_center.name or "",
                text_format,
            )

            worksheet.write_number(
                row,
                1,
                cost_center.planned_budget or 0,
                currency_format,
            )

            worksheet.write_number(
                row,
                2,
                cost_center.actual_cost or 0,
                currency_format,
            )

            worksheet.write_number(
                row,
                3,
                cost_center.budget_variance or 0,
                currency_format,
            )

            worksheet.write_number(
                row,
                4,
                cost_center.remaining_budget or 0,
                currency_format,
            )

            row += 1

        # ==========================
        # Totals
        # ==========================

        total_budget = sum(cost_centers.mapped("planned_budget"))
        total_actual = sum(cost_centers.mapped("actual_cost"))
        total_variance = sum(cost_centers.mapped("budget_variance"))
        total_remaining = sum(cost_centers.mapped("remaining_budget"))

        worksheet.write(
            row,
            0,
            "TOTAL",
            total_text_format,
        )

        worksheet.write_number(
            row,
            1,
            total_budget,
            total_currency_format,
        )

        worksheet.write_number(
            row,
            2,
            total_actual,
            total_currency_format,
        )

        worksheet.write_number(
            row,
            3,
            total_variance,
            total_currency_format,
        )

        worksheet.write_number(
            row,
            4,
            total_remaining,
            total_currency_format,
        )

        # ==========================
        # Report Summary
        # ==========================

        worksheet.write(
            row + 2,
            0,
            "Total Cost Centers:",
            info_label_format,
        )

        worksheet.write(
            row + 2,
            1,
            len(cost_centers),
            info_label_format,
        )

        # ==========================
        # Excel Features
        # ==========================

        worksheet.freeze_panes(6, 0)

        if cost_centers:
            worksheet.autofilter(
                5,
                0,
                row - 1,
                4,
            )

        worksheet.write(
            row + 4,
            0,
            "Generated from Construction Management System",
            footer_format,
        )

        workbook.close()

        output.seek(0)

        filename = f"Budget_vs_Actual_Report_{fields.Date.today()}.xlsx"

        attachment = self.env["ir.attachment"].create({
            "name": filename,
            "type": "binary",
            "datas": base64.b64encode(output.read()),
            "mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        })

        return {
            "type": "ir.actions.act_url",
            "url": f"/web/content/{attachment.id}?download=true",
            "target": "self",
        }