from odoo import fields, models
import io
import base64
import xlsxwriter


class MaterialConsumptionReport(models.TransientModel):
    _name = "material.consumption.report"
    _description = "Material Consumption Report"

    name = fields.Char(
        string="Report Name",
        default="Material Consumption Report",
        readonly=True,
    )

    def action_export_excel(self):
        self.ensure_one()

        output = io.BytesIO()

        workbook = xlsxwriter.Workbook(
            output,
            {"in_memory": True}
        )

        worksheet = workbook.add_worksheet(
            "Material Consumption"
        )

        worksheet.center_horizontally()

        worksheet.set_row(0, 28)
        worksheet.set_row(1, 22)
        worksheet.set_row(5, 22)

        # ==========================
        # Formats
        # ==========================

        title_format = workbook.add_format({
            "bold": True,
            "font_size": 18,
            "font_color": "white",
            "bg_color": "#1F4E78",
            "align": "center",
            "valign": "vcenter",
        })

        report_title_format = workbook.add_format({
            "bold": True,
            "font_size": 13,
            "font_color": "#1F1F1F",
            "bg_color": "#D9EAD3",
            "border": 1,
            "align": "center",
            "valign": "vcenter",
        })

        header_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#4472C4",
            "border": 1,
            "align": "center",
            "valign": "vcenter",
        })

        text_format = workbook.add_format({
            "border": 1,
            "align": "left",
            "valign": "vcenter",
        })

        number_format = workbook.add_format({
            "border": 1,
            "align": "right",
            "num_format": "#,##0.00",
        })

        total_text_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#305496",
            "border": 1,
            "align": "center",
        })

        total_number_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#305496",
            "border": 1,
            "align": "right",
            "num_format": "#,##0.00",
        })

        info_label_format = workbook.add_format({
            "bold": True,
        })

        footer_format = workbook.add_format({
            "italic": True,
            "font_color": "#808080",
        })

        # ==========================
        # Company
        # ==========================

        company = self.env.company

        worksheet.merge_range(
            "A1:H1",
            company.name,
            title_format,
        )

        worksheet.merge_range(
            "A2:H2",
            "Material Consumption Report",
            report_title_format,
        )

        worksheet.write(
            "A4",
            "Report Date:",
            info_label_format,
        )

        worksheet.write(
            "B4",
            str(fields.Date.today())
        )

        worksheet.write(
            "G4",
            "Generated By:",
            info_label_format,
        )

        worksheet.write(
            "H4",
            self.env.user.name
        )

        headers = [
            "Material Request",
            "Project",
            "Cost Center",
            "Product",
            "Planned Quantity",
            "Issued Quantity",
            "Remaining Quantity",
            "Status",
        ]

        for col, header in enumerate(headers):
            worksheet.write(
                5,
                col,
                header,
                header_format,
            )

        worksheet.set_column("A:A", 18)
        worksheet.set_column("B:B", 22)
        worksheet.set_column("C:C", 20)
        worksheet.set_column("D:D", 25)
        worksheet.set_column("E:G", 18)
        worksheet.set_column("H:H", 15)

        requests = self.env[
            "construction.material.request"
        ].search([])

        row = 6

        total_planned = 0
        total_issued = 0
        total_remaining = 0

        for request in requests:

            for line in request.line_ids:

                moves = self.env["stock.move"].search([
                    ("cost_center_id", "=", request.cost_center_id.id),
                    ("product_id", "=", line.product_id.id),
                    ("state", "=", "done"),
                ])

                issued_qty = sum(
                    moves.mapped("product_uom_qty")
                )

                remaining_qty = (
                    line.quantity - issued_qty
                )

                worksheet.write(
                    row,
                    0,
                    request.name,
                    text_format,
                )

                worksheet.write(
                    row,
                    1,
                    request.project_id.name or "",
                    text_format,
                )

                worksheet.write(
                    row,
                    2,
                    request.cost_center_id.name or "",
                    text_format,
                )

                worksheet.write(
                    row,
                    3,
                    line.product_id.display_name or "",
                    text_format,
                )

                worksheet.write_number(
                    row,
                    4,
                    line.quantity,
                    number_format,
                )

                worksheet.write_number(
                    row,
                    5,
                    issued_qty,
                    number_format,
                )

                worksheet.write_number(
                    row,
                    6,
                    remaining_qty,
                    number_format,
                )

                worksheet.write(
                    row,
                    7,
                    dict(
                        request._fields["state"].selection
                    ).get(request.state),
                    text_format,
                )

                total_planned += line.quantity
                total_issued += issued_qty
                total_remaining += remaining_qty

                row += 1

            
        # ==========================
        # Totals
        # ==========================

        worksheet.write(
            row,
            0,
            "TOTAL",
            total_text_format,
        )

        worksheet.write_blank(
            row,
            1,
            "",
            total_text_format,
        )

        worksheet.write_blank(
            row,
            2,
            "",
            total_text_format,
        )

        worksheet.write_blank(
            row,
            3,
            "",
            total_text_format,
        )

        worksheet.write_number(
            row,
            4,
            total_planned,
            total_number_format,
        )

        worksheet.write_number(
            row,
            5,
            total_issued,
            total_number_format,
        )

        worksheet.write_number(
            row,
            6,
            total_remaining,
            total_number_format,
        )

        worksheet.write_blank(
            row,
            7,
            "",
            total_text_format,
        )

        # ==========================
        # Summary
        # ==========================

        worksheet.write(
            row + 2,
            0,
            "Material Requests:",
            info_label_format,
        )

        worksheet.write(
            row + 2,
            1,
            len(requests),
        )

        worksheet.write(
            row + 3,
            0,
            "Total Lines:",
            info_label_format,
        )

        worksheet.write(
            row + 3,
            1,
            sum(len(r.line_ids) for r in requests),
        )

        # ==========================
        # Excel Features
        # ==========================

        worksheet.freeze_panes(6, 0)

        if row > 6:
            worksheet.autofilter(
                5,
                0,
                row - 1,
                7,
            )

        worksheet.write(
            row + 5,
            0,
            "Generated from Construction Management System",
            footer_format,
        )

        workbook.close()

        output.seek(0)

        filename = (
            f"Material_Consumption_Report_{fields.Date.today()}.xlsx"
        )

        attachment = self.env[
            "ir.attachment"
        ].create({
            "name": filename,
            "type": "binary",
            "datas": base64.b64encode(
                output.read()
            ),
            "mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        })

        return {
            "type": "ir.actions.act_url",
            "url": f"/web/content/{attachment.id}?download=true",
            "target": "self",
        }

            