from odoo import fields, models
import io
import base64
import xlsxwriter


class ProjectProgressReport(models.TransientModel):

    _name = "project.progress.report"
    _description = "Project Progress Report"


    name = fields.Char(
        string="Report Name",
        default="Project Progress Report",
        readonly=True,
    )


    def action_export_excel(self):

        self.ensure_one()

        output = io.BytesIO()

        workbook = xlsxwriter.Workbook(
            output,
            {"in_memory": True}
        )

        worksheet = workbook.add_worksheet(
            "Project Progress"
        )


        worksheet.center_horizontally()

        worksheet.set_row(0,28)
        worksheet.set_row(1,22)
        worksheet.set_row(5,22)


        # ==========================
        # Formats
        # ==========================


        title_format = workbook.add_format({
            "bold": True,
            "font_size":18,
            "font_color":"white",
            "bg_color":"#1F4E78",
            "align":"center",
            "valign":"vcenter",
        })


        report_title_format = workbook.add_format({
            "bold":True,
            "font_size":13,
            "bg_color":"#D9EAD3",
            "border":1,
            "align":"center",
        })


        header_format = workbook.add_format({
            "bold":True,
            "font_color":"white",
            "bg_color":"#4472C4",
            "border":1,
            "align":"center",
        })


        text_format = workbook.add_format({
            "border":1,
        })


        currency_format = workbook.add_format({
            "border":1,
            "num_format":"#,##0.00",
        })


        percent_format = workbook.add_format({
            "border":1,
            "num_format":"0.00",
        })


        total_text_format = workbook.add_format({
            "bold":True,
            "font_color":"white",
            "bg_color":"#305496",
            "border":1,
        })


        total_currency_format = workbook.add_format({
            "bold":True,
            "font_color":"white",
            "bg_color":"#305496",
            "border":1,
            "num_format":"#,##0.00",
        })


        info_label_format = workbook.add_format({
            "bold":True,
        })


        footer_format = workbook.add_format({
            "italic":True,
            "font_color":"#808080",
        })



        # ==========================
        # Header
        # ==========================


        company = self.env.company


        worksheet.merge_range(
            "A1:H1",
            company.name,
            title_format
        )


        worksheet.merge_range(
            "A2:H2",
            "Project Progress Report",
            report_title_format
        )


        worksheet.write(
            "A4",
            "Report Date:",
            info_label_format
        )


        worksheet.write(
            "B4",
            str(fields.Date.today())
        )


        worksheet.write(
            "D4",
            "Generated By:",
            info_label_format
        )


        worksheet.write(
            "E4",
            self.env.user.name
        )



        # ==========================
        # Headers
        # ==========================


        headers = [

            "Project",
            "Contract",
            "Customer",
            "Contract Value",
            "Actual Progress %",
            "Completed Amount",
            "Remaining Amount",
            "Status",

        ]


        for col,header in enumerate(headers):

            worksheet.write(
                5,
                col,
                header,
                header_format
            )


        worksheet.set_column("A:A",30)
        worksheet.set_column("B:C",25)
        worksheet.set_column("D:G",20)
        worksheet.set_column("H:H",15)



        # ==========================
        # Data
        # ==========================


        projects = self.env[
            "project.project"
        ].search([])


        row = 6


        total_contract = 0
        total_completed = 0



        for project in projects:


            contract = project.contract_id


            if not contract:
                continue


            billings = self.env[
                "construction.progress.billing"
            ].search([
                ("project_id","=",project.id),
                ("state","in",
                 [
                    "approved",
                    "invoiced"
                 ])
            ])


            actual_progress = sum(
                billings.mapped(
                    "progress_percentage"
                )
            )


            completed_amount = (
                contract.contract_value *
                actual_progress /
                100
            )


            remaining_amount = (
                contract.contract_value -
                completed_amount
            )



            values = [

                project.name,

                contract.name,

                contract.customer_id.name,

                contract.contract_value,

                actual_progress,

                completed_amount,

                remaining_amount,

                contract.state,

            ]


            for col,value in enumerate(values):


                if col in [3,5,6]:

                    worksheet.write_number(
                        row,
                        col,
                        value or 0,
                        currency_format
                    )

                elif col == 4:

                    worksheet.write_number(
                        row,
                        col,
                        value or 0,
                        percent_format
                    )

                else:

                    worksheet.write(
                        row,
                        col,
                        value or "",
                        text_format
                    )


            total_contract += contract.contract_value
            total_completed += completed_amount


            row +=1




        # ==========================
        # Total
        # ==========================


        worksheet.write(
            row,
            0,
            "TOTAL",
            total_text_format
        )


        worksheet.write_number(
            row,
            3,
            total_contract,
            total_currency_format
        )


        worksheet.write_number(
            row,
            5,
            total_completed,
            total_currency_format
        )



        worksheet.freeze_panes(
            6,
            0
        )


        workbook.close()


        output.seek(0)


        filename = (
            f"Project_Progress_Report_"
            f"{fields.Date.today()}.xlsx"
        )


        attachment = self.env[
            "ir.attachment"
        ].create({

            "name":filename,

            "type":"binary",

            "datas":
            base64.b64encode(
                output.read()
            ),

            "mimetype":
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

        })


        return {

            "type":
            "ir.actions.act_url",

            "url":
            f"/web/content/{attachment.id}?download=true",

            "target":"self",

        }