from odoo import fields, models
import io
import base64
import xlsxwriter


class ProjectProfitabilityReport(models.TransientModel):
    _name = "project.profitability.report"
    _description = "Project Profitability Report"

    name = fields.Char(
        default="Project Profitability Report",
        readonly=True,
    )

    def action_export_excel(self):
        self.ensure_one()

        output = io.BytesIO()

        workbook = xlsxwriter.Workbook(
            output,
            {"in_memory": True},
        )

        worksheet = workbook.add_worksheet(
            "Project Profitability"
        )

        worksheet.center_horizontally()

        # ==========================
        # Formats
        # ==========================

        title = workbook.add_format({
            "bold": True,
            "font_size": 18,
            "font_color": "white",
            "bg_color": "#1F4E78",
            "align": "center",
            "valign": "vcenter",
        })

        report = workbook.add_format({
            "bold": True,
            "font_size": 13,
            "bg_color": "#D9EAD3",
            "border": 1,
            "align": "center",
        })

        header = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#4472C4",
            "border": 1,
            "align": "center",
        })

        text = workbook.add_format({
            "border": 1,
        })

        money = workbook.add_format({
            "border": 1,
            "num_format": "#,##0.00",
        })

        percent = workbook.add_format({
            "border": 1,
            "num_format": "0.00%",
        })

        total_text = workbook.add_format({
            "bold": True,
            "bg_color": "#305496",
            "font_color": "white",
            "border": 1,
            "align": "center",
        })

        total_money = workbook.add_format({
            "bold": True,
            "bg_color": "#305496",
            "font_color": "white",
            "border": 1,
            "num_format": "#,##0.00",
        })

        total_percent = workbook.add_format({
            "bold": True,
            "bg_color": "#305496",
            "font_color": "white",
            "border": 1,
            "num_format": "0.00%",
        })

        # ==========================
        # Header
        # ==========================

        worksheet.merge_range(
            "A1:F1",
            self.env.company.name,
            title,
        )

        worksheet.merge_range(
            "A2:F2",
            "Project Profitability Report",
            report,
        )

        worksheet.write("A4", "Date")
        worksheet.write("B4", str(fields.Date.today()))

        worksheet.write("D4", "Generated By")
        worksheet.write("E4", self.env.user.name)

        headers = [
            "Project",
            "Contract Revenue",
            "Billed Revenue",
            "Total Cost",
            "Profit",
            "Profit Margin %",
        ]

        for col, value in enumerate(headers):
            worksheet.write(5, col, value, header)

        worksheet.set_column("A:A", 35)
        worksheet.set_column("B:F", 20)

        # ==========================
        # Data
        # ==========================

        row = 6

        total_contract = 0
        total_billed = 0
        total_cost = 0
        total_profit = 0

        projects = self.env["project.project"].search([])

        for project in projects:

            contract = project.contract_id

            contract_revenue = (
                contract.contract_value
                if contract
                else 0
            )

            billed_revenue = sum(
                self.env["account.move"].search([
                    ("project_id", "=", project.id),
                    ("move_type", "=", "out_invoice"),
                    ("state", "=", "posted"),
                ]).mapped("amount_untaxed")
            )

            cost = sum(
                project.cost_center_ids.mapped(
                    "actual_cost"
                )
            )

            profit = billed_revenue - cost

            margin = 0

            if billed_revenue:
                margin = profit / billed_revenue

            worksheet.write(
                row,
                0,
                project.name,
                text,
            )

            worksheet.write_number(
                row,
                1,
                contract_revenue,
                money,
            )

            worksheet.write_number(
                row,
                2,
                billed_revenue,
                money,
            )

            worksheet.write_number(
                row,
                3,
                cost,
                money,
            )

            worksheet.write_number(
                row,
                4,
                profit,
                money,
            )

            worksheet.write_number(
                row,
                5,
                margin,
                percent,
            )

            total_contract += contract_revenue
            total_billed += billed_revenue
            total_cost += cost
            total_profit += profit

            row += 1

        total_margin = 0

        if total_billed:
            total_margin = total_profit / total_billed

        worksheet.write(
            row,
            0,
            "TOTAL",
            total_text,
        )

        worksheet.write_number(
            row,
            1,
            total_contract,
            total_money,
        )

        worksheet.write_number(
            row,
            2,
            total_billed,
            total_money,
        )

        worksheet.write_number(
            row,
            3,
            total_cost,
            total_money,
        )

        worksheet.write_number(
            row,
            4,
            total_profit,
            total_money,
        )

        worksheet.write_number(
            row,
            5,
            total_margin,
            total_percent,
        )

        worksheet.freeze_panes(6, 0)

        if row > 6:
            worksheet.autofilter(
                5,
                0,
                row - 1,
                5,
            )

        workbook.close()

        output.seek(0)

        attachment = self.env["ir.attachment"].create({
            "name": f"Project_Profitability_{fields.Date.today()}.xlsx",
            "type": "binary",
            "datas": base64.b64encode(output.read()),
            "mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        })

        return {
            "type": "ir.actions.act_url",
            "url": f"/web/content/{attachment.id}?download=true",
            "target": "self",
        }