from odoo import fields, models
import io
import base64
import xlsxwriter

class PurchaseOrderReport(models.TransientModel):
    _name = "purchase.order.report"
    _description = "Purchase Order Report"

    name = fields.Char(
        default="Purchase Order Report",
        readonly=True,
    )

    def action_export_excel(self):
        self.ensure_one()

        output = io.BytesIO()

        workbook = xlsxwriter.Workbook(
            output,
            {"in_memory": True},
        )

        worksheet = workbook.add_worksheet(
            "Purchase Orders"
        )

        worksheet.center_horizontally()

        title_format = workbook.add_format({
            "bold": True,
            "font_size": 18,
            "font_color": "white",
            "bg_color": "#1F4E78",
            "align": "center",
            "valign": "vcenter",
        })

        report_title_format = workbook.add_format({
            "bold": True,
            "font_size": 13,
            "bg_color": "#D9EAD3",
            "border": 1,
            "align": "center",
        })

        header_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#4472C4",
            "border": 1,
            "align": "center",
        })

        text_format = workbook.add_format({
            "border": 1,
        })

        currency_format = workbook.add_format({
            "border": 1,
            "num_format": "#,##0.00",
            "align": "right",
        })

        total_text = workbook.add_format({
            "bold": True,
            "bg_color": "#305496",
            "font_color": "white",
            "border": 1,
            "align": "center",
        })

        total_currency = workbook.add_format({
            "bold": True,
            "bg_color": "#305496",
            "font_color": "white",
            "border": 1,
            "num_format": "#,##0.00",
        })

        company = self.env.company

        worksheet.merge_range(
            "A1:H1",
            company.name,
            title_format,
        )

        worksheet.merge_range(
            "A2:H2",
            "Purchase Order Report",
            report_title_format,
        )

        worksheet.write("A4", "Report Date")
        worksheet.write("B4", str(fields.Date.today()))
        worksheet.write("G4", "Generated By")
        worksheet.write("H4", self.env.user.name)

        headers = [
            "PO Number",
            "Vendor",
            "Project",
            "Cost Center",
            "Material Request",
            "Order Status",
            "Delivery Status",
            "Total Amount",
        ]

        for col, header in enumerate(headers):
            worksheet.write(
                5,
                col,
                header,
                header_format,
            )

        worksheet.set_column("A:H", 22)

        orders = self.env[
            "purchase.order"
        ].search([])

        states = dict(
            self.env["purchase.order"]
            ._fields["state"].selection
        )

        row = 6

        for order in orders:

            if not order.picking_ids:
                delivery = "No Delivery"

            elif all(
                p.state == "done"
                for p in order.picking_ids
            ):
                delivery = "Delivered"

            else:
                delivery = "Waiting"

            worksheet.write(
                row, 0,
                order.name or "",
                text_format,
            )

            worksheet.write(
                row, 1,
                order.partner_id.name or "",
                text_format,
            )

            worksheet.write(
                row, 2,
                order.cost_center_id.project_id.name or "",
                text_format,
            )

            worksheet.write(
                row, 3,
                order.cost_center_id.name or "",
                text_format,
            )

            worksheet.write(
                row, 4,
                order.material_request_id.name or "",
                text_format,
            )

            worksheet.write(
                row, 5,
                states.get(order.state, ""),
                text_format,
            )

            worksheet.write(
                row, 6,
                delivery,
                text_format,
            )

            worksheet.write_number(
                row, 7,
                order.amount_total,
                currency_format,
            )

            row += 1

        worksheet.write(
            row,
            0,
            "TOTAL",
            total_text,
        )

        worksheet.write_number(
            row,
            7,
            sum(orders.mapped("amount_total")),
            total_currency,
        )

        worksheet.freeze_panes(6, 0)

        if orders:
            worksheet.autofilter(
                5,
                0,
                row - 1,
                7,
            )

        workbook.close()

        output.seek(0)

        attachment = self.env[
            "ir.attachment"
        ].create({
            "name": f"Purchase_Order_Report_{fields.Date.today()}.xlsx",
            "type": "binary",
            "datas": base64.b64encode(output.read()),
            "mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        })

        return {
            "type": "ir.actions.act_url",
            "url": f"/web/content/{attachment.id}?download=true",
            "target": "self",
        }