from odoo import fields, models
import io
import base64
import xlsxwriter


class VariationOrderReport(models.TransientModel):
    _name = "variation.order.report"
    _description = "Variation Order Report"

    name = fields.Char(
        string="Report Name",
        default="Variation Order Report",
        readonly=True,
    )

    def action_export_excel(self):
        self.ensure_one()

        output = io.BytesIO()

        workbook = xlsxwriter.Workbook(
            output,
            {"in_memory": True},
        )

        worksheet = workbook.add_worksheet(
            "Variation Orders"
        )

        worksheet.center_horizontally()
        worksheet.set_row(0, 28)
        worksheet.set_row(1, 22)
        worksheet.set_row(5, 22)

        # ==========================
        # Formats
        # ==========================

        title_format = workbook.add_format({
            "bold": True,
            "font_size": 18,
            "font_color": "white",
            "bg_color": "#1F4E78",
            "align": "center",
            "valign": "vcenter",
        })

        report_title_format = workbook.add_format({
            "bold": True,
            "font_size": 13,
            "font_color": "#1F1F1F",
            "bg_color": "#D9EAD3",
            "border": 1,
            "align": "center",
            "valign": "vcenter",
        })

        header_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#4472C4",
            "border": 1,
            "align": "center",
            "valign": "vcenter",
        })

        text_format = workbook.add_format({
            "border": 1,
            "align": "left",
            "valign": "vcenter",
        })

        currency_format = workbook.add_format({
            "border": 1,
            "align": "right",
            "num_format": "#,##0.00",
        })

        total_text_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#305496",
            "border": 1,
            "align": "center",
        })

        total_currency_format = workbook.add_format({
            "bold": True,
            "font_color": "white",
            "bg_color": "#305496",
            "border": 1,
            "align": "right",
            "num_format": "#,##0.00",
        })

        info_label_format = workbook.add_format({
            "bold": True,
        })

        footer_format = workbook.add_format({
            "italic": True,
            "font_color": "#808080",
        })

        # ==========================
        # Company & Report Title
        # ==========================

        company = self.env.company

        worksheet.merge_range(
            "A1:H1",
            company.name,
            title_format,
        )

        worksheet.merge_range(
            "A2:H2",
            "Variation Order Report",
            report_title_format,
        )

        # ==========================
        # Report Information
        # ==========================

        worksheet.write(
            "A4",
            "Report Date:",
            info_label_format,
        )

        worksheet.write(
            "B4",
            str(fields.Date.today()),
        )

        worksheet.write(
            "G4",
            "Generated By:",
            info_label_format,
        )

        worksheet.write(
            "H4",
            self.env.user.name,
        )

        # ==========================
        # Headers
        # ==========================

        headers = [
            "Variation No",
            "Project",
            "Contract",
            "Description",
            "Variation Value",
            "Contract Impact",
            "Status",
            "Invoice Status",
        ]

        for col, header in enumerate(headers):
            worksheet.write(
                5,
                col,
                header,
                header_format,
            )

        # ==========================
        # Column Width
        # ==========================

        worksheet.set_column("A:A", 20)
        worksheet.set_column("B:C", 25)
        worksheet.set_column("D:D", 40)
        worksheet.set_column("E:F", 18)
        worksheet.set_column("G:H", 18)

        # ==========================
        # Data
        # ==========================

        variation_orders = self.env[
            "construction.variation.order"
        ].search([])

        states = dict(
            self.env[
                "construction.variation.order"
            ]._fields["state"].selection
        )

        payment_states = dict(
            self.env[
                "account.move"
            ]._fields["payment_state"].selection
        )

        row = 6

        for variation in variation_orders:

            worksheet.write(
                row,
                0,
                variation.name or "",
                text_format,
            )

            worksheet.write(
                row,
                1,
                variation.project_id.name or "",
                text_format,
            )

            worksheet.write(
                row,
                2,
                variation.contract_id.name or "",
                text_format,
            )

            worksheet.write(
                row,
                3,
                variation.description or "",
                text_format,
            )

            worksheet.write_number(
                row,
                4,
                variation.amount or 0,
                currency_format,
            )

            worksheet.write_number(
                row,
                5,
                variation.contract_id.contract_value or 0,
                currency_format,
            )

            worksheet.write(
                row,
                6,
                states.get(
                    variation.state,
                    "",
                ),
                text_format,
            )

            if variation.invoice_id:
                invoice_status = payment_states.get(
                    variation.invoice_id.payment_state,
                    "",
                )
            else:
                invoice_status = "No Invoice"

            worksheet.write(
                row,
                7,
                invoice_status,
                text_format,
            )

            row += 1

        # ==========================
        # Totals
        # ==========================

        total_variation = sum(
            variation_orders.mapped("amount")
        )

        worksheet.write(
            row,
            0,
            "TOTAL",
            total_text_format,
        )

        worksheet.write_blank(
            row,
            1,
            "",
            total_text_format,
        )

        worksheet.write_blank(
            row,
            2,
            "",
            total_text_format,
        )

        worksheet.write_blank(
            row,
            3,
            "",
            total_text_format,
        )

        worksheet.write_number(
            row,
            4,
            total_variation,
            total_currency_format,
        )

        worksheet.write_blank(
            row,
            5,
            "",
            total_currency_format,
        )

        worksheet.write_blank(
            row,
            6,
            "",
            total_text_format,
        )

        worksheet.write_blank(
            row,
            7,
            "",
            total_text_format,
        )

        # ==========================
        # Summary
        # ==========================

        worksheet.write(
            row + 2,
            0,
            "Total Variation Orders:",
            info_label_format,
        )

        worksheet.write(
            row + 2,
            1,
            len(variation_orders),
            info_label_format,
        )

        # ==========================
        # Excel Features
        # ==========================

        worksheet.freeze_panes(6, 0)

        if variation_orders:
            worksheet.autofilter(
                5,
                0,
                row - 1,
                7,
            )

        worksheet.write(
            row + 4,
            0,
            "Generated from Construction Management System",
            footer_format,
        )

        workbook.close()

        output.seek(0)

        filename = (
            f"Variation_Order_Report_{fields.Date.today()}.xlsx"
        )

        attachment = self.env[
            "ir.attachment"
        ].create({
            "name": filename,
            "type": "binary",
            "datas": base64.b64encode(
                output.read()
            ),
            "mimetype": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        })

        return {
            "type": "ir.actions.act_url",
            "url": f"/web/content/{attachment.id}?download=true",
            "target": "self",
        }